# -*- coding: utf-8 -*-

URL_RESET_PERIOD = '60'

PROC_TOTAL_LIMIT = 1 # 每台IP所有的端口号限制在20 ，可以继续提高了。
PROC_BFS_LIMIT = 3  # 会限制进程子进程的数量了
PROC_DFS_LIMIT = 5 
TRY_TIMES = 3

CONTROLLER_HOST = '192.168.36.201'
CONTROLLER_PORT = 7020

ST_DIR = '/scrapy'

URLS_LIMIT = 2 
PROC_WAIT = 2
PROC_STABLE = 4
PROC_SPEED = 8